Update patch set 6
Patch Set 6:

> Build Failed
 > 
 > https://jenkins.opendaylight.org/releng/job/genius-maven-verify-neon-mvn35-openjdk8/152/
 > : FAILURE
 > 
 > Sub-project  has 0 test failures and 1 tests in error. (
 > https://jenkins.opendaylight.org/releng/job/genius-maven-verify-neon-mvn35-openjdk8/152/
 > )
 > 
 > Logs: https://logs.opendaylight.org/releng/vex-yul-odl-jenkins-1/genius-maven-verify-neon-mvn35-openjdk8/152
 > 
 > https://jenkins.opendaylight.org/releng/job/genius-distribution-check-neon/153/
 > : SUCCESS
 > 
 > Logs: https://logs.opendaylight.org/releng/vex-yul-odl-jenkins-1/genius-distribution-check-neon/153
 > 
 > https://jenkins.opendaylight.org/releng/job/genius-maven-javadoc-verify-neon/155/
 > : SUCCESS
 > 
 > Logs: https://logs.opendaylight.org/releng/vex-yul-odl-jenkins-1/genius-maven-javadoc-verify-neon/155
 > 
 > https://jenkins.opendaylight.org/releng/job/genius-validate-autorelease-neon/38/
 > : SUCCESS
 > 
 > Logs: https://logs.opendaylight.org/releng/vex-yul-odl-jenkins-1/genius-validate-autorelease-neon/38

Michael,
I am seeing sometimes, ItmTest fails with below error:

testWiring(org.opendaylight.genius.itm.tests.ItmTest)  Time elapsed: 14.998 sec  <<< ERROR!
org.opendaylight.infrautils.testutils.LogCaptureRuleException: Expected no error log, but: configureTunnelType VXLAN failed for transportZone default-transport-zone
	at org.opendaylight.infrautils.testutils.LogCaptureRule$1.lambda$evaluate$0(LogCaptureRule.java:88)

Above error occurs rarely on this gerrit build, if i repeatedly run mvn test of this file locally on my system, it never fails.

It seems that during testWiring, the new logic of creating default-transport-zone in ItmProvider.java is getting executed which is halted in between when testWiring is done and clearCaches() happens and it fails.

Shall I put below to get it passing:

// wait for start-up default-TZ creation task to get over
coordinatorEventsWaiter.awaitEventsConsumption();

Patch-set: 6