Minor: Clean up fcapsmanager/countermanager POM
We should not be using this old outdated version of maven-bundle-plugin
here, but the one that odlparent provides.

Ran into this while testing Bug 7182 (but it's not directly related to
that), where I hit this problem in the Eclipse IDE:

Manifest org.opendaylight.genius:countermanager:bundle:0.2.0-SNAPSHOT :
Input file does not exist: target/classes/LICENSE

org.apache.maven.plugin.MojoExecutionException: Error(s) found in
manifest configuration

Change-Id: Ie67a1e8314e901b31e1908eacb1f611b9b671e41
Signed-off-by: Michael Vorburger <vorburger@redhat.com>