temporarily disable resourcemanager
[1] caused the exception below. Rather than revert the patch we will simply disable loading the feature.

java.lang.RuntimeException: java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.opendaylight.genius.interfacemanager.servicebinding.rev160406.service.bindings.ServicesInfoKey. Missing key is getServiceMode. Supplied key is ServicesInfoKey [_interfaceName=br-int]

[1] https://git.opendaylight.org/gerrit/#/c/40810/

Change-Id: Ie86557996f7bbe3d1c78ec7f6da2250b1a5e8800
Signed-off-by: Sam Hague <shague@redhat.com>