Update patch set 2
Patch Set 2: Code-Review-1

The patch leads to numerous exceptions around service binding:

018-02-24T14:03:53,041 | WARN  | opendaylight-cluster-data-shard-dispatcher-221 | ShardDataTree                    | 230 - org.opendaylight.controller.sal-distributed-datastore - 1.7.0.SNAPSHOT | member-1-shard-default-config: Store Tx member-1-datastore-config-fe-0-txn-3736-0: Data validation failed for path /(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-bindings/services-info/services-info[{(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)interface-name=41dec516-43b1-4821-b975-6e3c48afc0db, (urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-mode=(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-mode-egress}].
org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-bindings/services-info/services-info[{(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)interface-name=41dec516-43b1-4821-b975-6e3c48afc0db, (urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-mode=(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-mode-egress}] does not exist. Cannot apply modification to its children.
2018-02-24T14:03:53,047 | ERROR | opendaylight-cluster-data-akka.actor.default-dispatcher-47 | LocalThreePhaseCommitCohort      | 230 - org.opendaylight.controller.sal-distributed-datastore - 1.7.0.SNAPSHOT | Failed to prepare transaction member-1-datastore-config-fe-0-txn-3736-0 on backend
org.opendaylight.controller.md.sal.common.api.data.TransactionCommitFailedException: Data did not pass validation.
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [40:com.typesafe.akka.actor:2.5.4]
Caused by: org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-bindings/services-info/services-info[{(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)interface-name=41dec516-43b1-4821-b975-6e3c48afc0db, (urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-mode=(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-mode-egress}] does not exist. Cannot apply modification to its children.

Patch-set: 2
Reviewer: Gerrit User 773 <773@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Code-Review=-1