Update patch set 4
Patch Set 4:

FTR: This change requires any projects using IMdsalApiManager (i.e. netvirt) to be rebuilt with fresh JARs to de deployed; otherwise we hit a java.lang.NoSuchMethodError

Patch-set: 4