OVS Port Delete not going through
JIRA: GENIUS-133

Deletion of OVS port is resulting in the below error:

mainWorker=InterfaceStateRemoveWorker{nodeConnectorIdNew=Uri{_value=openflow:68797520762178:2},
nodeConnectorIdOld=Uri{_value=openflow:68797520762178:2}, fcNodeConnectorOld=FlowCapableNodeConnector{
getAdvertisedFeatures=PortFeatures{_tenMbHd=false, _tenMbFd=false, _hundredMbHd=false, _hundredMbFd=false,
_oneGbHd=false, _oneGbFd=false, _tenGbFd=false, _fortyGbFd=false, _hundredGbFd=false, _oneTbFd=false, _other=false,
_copper=false, _fiber=false, _autoeng=false, _pause=false, _pauseAsym=false}, getConfiguration=PortConfig{_pORTDOWN=false,
_nORECV=false, _nOFWD=false, _nOPACKETIN=false}, getCurrentFeature=PortFeatures{_tenMbHd=false, _tenMbFd=false,
_hundredMbHd=false, _hundredMbFd=false, _oneGbHd=false, _oneGbFd=false, _tenGbFd=false, _fortyGbFd=false,
_hundredGbFd=false, _oneTbFd=false, _other=false, _copper=false, _fiber=false, _autoeng=false, _pause=false,
_pauseAsym=false}, getCurrentSpeed=0, getHardwareAddress=MacAddress{_value=9a:be:c5:8b:90:d2}, getMaximumSpeed=0,
getName=tun704bde687e8, getPeerFeatures=PortFeatures{_tenMbHd=false, _tenMbFd=false, _hundredMbHd=false,
_hundredMbFd=false, _oneGbHd=false, _oneGbFd=false, _tenGbFd=false, _fortyGbFd=false, _hundredGbFd=false, _oneTbFd=false,
_other=false, _copper=false, _fiber=false, _autoeng=false, _pause=false, _pauseAsym=false}, getPortNumber=
PortNumberUni{_uint32=2}, getQueue=[], getReason=Delete, getState=State{isBlocked=false, isLinkDown=false,
isLive=false, augmentations={}}, getSupported=PortFeatures{_tenMbHd=false, _tenMbFd=false, _hundredMbHd=false,
_hundredMbFd=false,_oneGbHd=false, _oneGbFd=false, _tenGbFd=false, _fortyGbFd=false, _hundredGbFd=false,
_oneTbFd=false, _other=false, _copper=false, _fiber=false, _autoeng=false, _pause=false, _pauseAsym=false}},
interfaceName='tun704bde687e8'}, rollbackWorker=null, retryCount=6/6, futures=[com.google.common.util.concurrent.
ImmediateFuture$ImmediateFailedFuture@6a75e6cd[status=FAILURE, cause=[java.lang.UnsupportedOperationException: submit()
cannot be used inside a Managed[New]TransactionRunner]]]}
java.lang.UnsupportedOperationException: submit() cannot be used inside a Managed[New]TransactionRunner
	at org.opendaylight.genius.infra.NonSubmitCancelableReadWriteTransaction.submit(NonSubmitCancelableReadWriteTransaction.java:36) ~[332:org.opendaylight.genius.mdsalutil-api:0.5.0.SNAPSHOT]
	at org.opendaylight.genius.interfacemanager.listeners.InterfaceInventoryStateListener$InterfaceStateRemoveWorker.handleTunnelMonitoringRemoval(InterfaceInventoryStateListener.java:424) ~[?:?]
	at org.opendaylight.genius.interfacemanager.listeners.InterfaceInventoryStateListener$InterfaceStateRemoveWorker.lambda$removeInterfaceStateConfiguration$0(InterfaceInventoryStateListener.java:398) ~[?:?]
	at org.opendaylight.genius.infra.ManagedNewTransactionRunnerImpl.callWithNewReadWriteTransactionAndSubmit(ManagedNewTransactionRunnerImpl.java:63) [332:org.opendaylight.genius.mdsalutil-api:0.5.0.SNAPSHOT]
	at org.opendaylight.genius.interfacemanager.listeners.InterfaceInventoryStateListener$InterfaceStateRemoveWorker.removeInterfaceStateConfiguration(InterfaceInventoryStateListener.java:378) [326:org.opendaylight.genius.interfacemanager-impl:0.5.0.SNAPSHOT]
	at org.opendaylight.genius.interfacemanager.listeners.InterfaceInventoryStateListener$InterfaceStateRemoveWorker.call(InterfaceInventoryStateListener.java:355) [326:org.opendaylight.genius.interfacemanager-impl:0.5.0.SNAPSHOT]
	at org.opendaylight.genius.interfacemanager.listeners.InterfaceInventoryStateListener$InterfaceStateRemoveWorker.call(InterfaceInventoryStateListener.java:318) [326:org.opendaylight.genius.interfacemanager-impl:0.5.0.SNAPSHOT]
	at org.opendaylight.infrautils.jobcoordinator.internal.JobCoordinatorImpl$MainTask.runWithUncheckedExceptionLogging(JobCoordinatorImpl.java:401) [352:org.opendaylight.infrautils.jobcoordinator-impl:1.4.0.SNAPSHOT]
	at org.opendaylight.infrautils.utils.concurrent.LoggingUncaughtThreadDeathContextRunnable.run(LoggingUncaughtThreadDeathContextRunnable.java:60) [357:org.opendaylight.infrautils.util:1.4.0.SNAPSHOT]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:?]

Change-Id: I5d0e634bdf24f159f018ed8ff8bdf9cacd98a78a
Signed-off-by: Faseela K <faseela.k@ericsson.com>