Update patch set 1
Patch Set 1: Code-Review-1

New set of errors from this patch as below. These came out after the first test failures though, so I think there is a different problem in this patch also.

2017-11-01 14:16:47,640 | WARN  | d-dispatcher-155 | ShardDataTree                    | 218 - org.opendaylight.controller.sal-distributed-datastore - 1.7.0.SNAPSHOT | member-1-shard-default-operational: Store Tx member-1-datastore-operational-fe-0-txn-9012-0: Data validation failed for path /(urn:opendaylight:netvirt:l3vpn?revision=2013-09-11)prefix-to-interface/vpn-ids.
org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:opendaylight:netvirt:l3vpn?revision=2013-09-11)prefix-to-interface/vpn-ids does not exist. Cannot apply modification to its children.

Patch-set: 1
Reviewer: Gerrit User 773 <773@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Code-Review=-1