Update patch set 1
Patch Set 1: Code-Review-2

Some new exceptions popped up in the oxygen csit run. rerunning.

https://logs.opendaylight.org/releng/vex-yul-odl-jenkins-1/netvirt-csit-1node-openstack-queens-gate-stateful-oxygen/22/odl_1/odl1_karaf.log.gz

2018-03-06T18:56:39,696 | ERROR | ForkJoinPool-1-worker-2 | InterfaceStateChangeListener     | 367 - org.opendaylight.netvirt.vpnmanager-impl - 0.6.0.SNAPSHOT | InterfaceStateChangeListener: VrfEntries for 418adedf-46d8-4d20-9c51-88eef547f84d failed to store into destination Operational with exception: {}
java.util.concurrent.ExecutionException: OptimisticLockFailedException{message=Optimistic lock failed., errorList=[RpcError [message=Optimistic lock failed., severity=ERROR, errorType=APPLICATION, tag=resource-denied, applicationTag=null, info=null, cause=org.opendaylight.yangtools.yang.data.api.schema.tree.ConflictingModificationAppliedException: Node was created by other transaction.]]}
	at org.opendaylight.mdsal.common.api.MappingCheckedFuture.wrapInExecutionException(MappingCheckedFuture.java:66) ~[?:?]

Patch-set: 1
Label: Code-Review=-2