Update patch set 1
Patch Set 1:

ATTN Sam, based on last week's experience on master, this change is actually slightly more "dangerous" than it appears... after you merge this into stable/carbon (and then merge job passed), you HAVE to IMMEDIATELY launch a netvirt build and re-deploy (through some trivial change), so that the code which uses IMdsalApiManager gets recompiled.  If we don't do this, we'll hit the java.lang.NoSuchMethodError:
org.opendaylight.genius.mdsalutil.interfaces.IMdsalApiManager.installFlow(Lorg/opendaylight/genius/mdsalutil/FlowEntity;)V again...

Patch-set: 1